### ISSUE TITLE
ready-made container to try out?

### ISSUE THREAD

**Issue by tomByrer** [billywhizz/spindle#1]
Any Docker or Unikernal container do you care to share to run this under, or have suggestions?

Glad to see you're working on this; I hope it can catch on as a more resource efficient way to run JS!

**Comment by billywhizz** [comment]
hi tom. it should be easy to build it in most recent linux docker containers - e.g. ubuntu/debian. if you do a fully static build you can run it with google distroless static docker. i'll see if i can push up a working dockerfile for building over the weekend. it's only a little experiment right now, but i kinda like this approach. 

with some basic ffi/dynamic binding support it would be a nice toolkit for building small fast JS runtimes. what are you running on? mac? i don't think would be a lot of work to get something building for mac.

**Comment by billywhizz** [comment]
this should work. https://github.com/billywhizz/spindle/blob/main/docker/builder.dockerfile
